-   id: detect-key
    name: incolume detect private key
    description: detects the presence of private keys.
    entry: detect-key
    language: python
    types: [text]
-   id: check-valid-filenames
    name: incolume check if is valid filenames
    description: Guarantees valid filenames for Python.
    entry: is-valid-filename
    language: python
    types: [python]
    stages: [pre-commit, pre-push, manual]
-   id: effort-message
    name: incolume effort message
    description: Effort message for commit.
    entry: effort-msg
    language: python
    types: [python]
    stages: [pre-commit, pre-push, manual]